import avatar1 from '../../assets/images/avatar/avatar-s-1.jpg';
import avatar2 from '../../assets/images/avatar/avatar-s-2.jpg';
import avatar3 from '../../assets/images/avatar/avatar-s-3.jpg';
import avatar4 from '../../assets/images/avatar/avatar-s-4.jpg';
import avatar5 from '../../assets/images/avatar/avatar-s-5.jpg';
import avatar6 from '../../assets/images/avatar/avatar-s-6.jpg';
import avatar7 from '../../assets/images/avatar/avatar-s-7.jpg';
import avatar8 from '../../assets/images/avatar/avatar-s-8.jpg';
import avatar9 from '../../assets/images/avatar/avatar-s-9.jpg';
const ContactsData = [
  {
    "contact_id": "61b8b5225048b709cadc4ce3",
    "contact_name": "Murray",
    "company_name": "DANJA",
    "contact_type": "customer",
    "status": false,
    "payment_terms": 9,
    "payment_terms_label": "Tempor dolore aliqua ex culpa enim adipisicing ullamco minim eu consequat fugiat do qui deserunt.",
    "currency_id": "61b8b5227a840077b5736825",
    "currency_code": "USD",
    "outstanding_receivable_amount": 0,
    "unused_credits_receivable_amount": 9.2535,
    "avatar": "https://i.pravatar.cc/150?img=6",
    "first_name": "Louise ",
    "last_name": " Lyons",
    "email": "louiselyons@danja.com",
    "phone": "+1 (887) 400-3272",
    "mobile": "+1 (807) 549-3329",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b52259ece77173779b25",
    "contact_name": "Caldwell",
    "company_name": "MANGLO",
    "contact_type": "customer",
    "status": false,
    "payment_terms": 0,
    "payment_terms_label": "Occaecat voluptate enim consequat ea qui dolore.",
    "currency_id": "61b8b522774ab16f9b6e9487",
    "currency_code": "USD",
    "outstanding_receivable_amount": 7,
    "unused_credits_receivable_amount": 2.2343,
    "avatar": "https://i.pravatar.cc/150?img=8",
    "first_name": "Andrews ",
    "last_name": " Rowland",
    "email": "andrewsrowland@manglo.com",
    "phone": "+1 (925) 404-3644",
    "mobile": "+1 (805) 442-3101",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b522e23ca4d6b178b3b9",
    "contact_name": "Mandy",
    "company_name": "GEEKOLOGY",
    "contact_type": "customer",
    "status": false,
    "payment_terms": 7,
    "payment_terms_label": "Labore enim aliquip consequat veniam quis adipisicing.",
    "currency_id": "61b8b52216b38ecf1598c7fe",
    "currency_code": "USD",
    "outstanding_receivable_amount": 0,
    "unused_credits_receivable_amount": 1.6451,
    "avatar": "https://i.pravatar.cc/150?img=9",
    "first_name": "Camille ",
    "last_name": " Cooley",
    "email": "camillecooley@geekology.com",
    "phone": "+1 (883) 573-3441",
    "mobile": "+1 (951) 475-3920",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b522f6c16a4b37a949b8",
    "contact_name": "Graham",
    "company_name": "KYAGORO",
    "contact_type": "customer",
    "status": true,
    "payment_terms": 4,
    "payment_terms_label": "Nulla nisi occaecat ea reprehenderit pariatur aliquip pariatur eu aliqua dolor.",
    "currency_id": "61b8b52246201dc98f3dafec",
    "currency_code": "USD",
    "outstanding_receivable_amount": 0,
    "unused_credits_receivable_amount": 0.795,
    "avatar": "https://i.pravatar.cc/150?img=7",
    "first_name": "Marissa ",
    "last_name": " Nielsen",
    "email": "marissanielsen@kyagoro.com",
    "phone": "+1 (859) 441-2635",
    "mobile": "+1 (915) 480-2910",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b522ef7278ce35e7d2d8",
    "contact_name": "Madeline",
    "company_name": "VOLAX",
    "contact_type": "customer",
    "status": true,
    "payment_terms": 4,
    "payment_terms_label": "Ut aute elit magna velit ea cupidatat exercitation labore consequat enim.",
    "currency_id": "61b8b5226956f2791afd6f2b",
    "currency_code": "USD",
    "outstanding_receivable_amount": 0,
    "unused_credits_receivable_amount": 5.0003,
    "avatar": "https://i.pravatar.cc/150?img=3",
    "first_name": "Chrystal ",
    "last_name": " Yates",
    "email": "chrystalyates@volax.com",
    "phone": "+1 (969) 461-2923",
    "mobile": "+1 (893) 508-3203",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b5221d7ac7af11d9bd83",
    "contact_name": "Lilia",
    "company_name": "REPETWIRE",
    "contact_type": "customer",
    "status": false,
    "payment_terms": 9,
    "payment_terms_label": "Laboris consequat qui laborum dolor sit sit sunt veniam proident incididunt est nisi dolore quis.",
    "currency_id": "61b8b522b2143c5e88caf54f",
    "currency_code": "USD",
    "outstanding_receivable_amount": 2,
    "unused_credits_receivable_amount": 0.1206,
    "avatar": "https://i.pravatar.cc/150?img=6",
    "first_name": "Manuela ",
    "last_name": " Barnett",
    "email": "manuelabarnett@repetwire.com",
    "phone": "+1 (967) 410-3786",
    "mobile": "+1 (982) 552-2922",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b5225fc188b70c96f40d",
    "contact_name": "Lolita",
    "company_name": "BLEEKO",
    "contact_type": "customer",
    "status": false,
    "payment_terms": 9,
    "payment_terms_label": "Ex veniam id amet id fugiat consectetur non id fugiat id mollit labore deserunt est.",
    "currency_id": "61b8b522ee245925e18ba7a4",
    "currency_code": "USD",
    "outstanding_receivable_amount": 3,
    "unused_credits_receivable_amount": 8.2953,
    "avatar": "https://i.pravatar.cc/150?img=2",
    "first_name": "Levine ",
    "last_name": " Keller",
    "email": "levinekeller@bleeko.com",
    "phone": "+1 (808) 594-2402",
    "mobile": "+1 (905) 476-3182",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b522b615a50fdf2da350",
    "contact_name": "Beck",
    "company_name": "DANCERITY",
    "contact_type": "customer",
    "status": true,
    "payment_terms": 2,
    "payment_terms_label": "Ad aute aliquip amet incididunt deserunt laboris.",
    "currency_id": "61b8b522fddce96c4647af51",
    "currency_code": "USD",
    "outstanding_receivable_amount": 4,
    "unused_credits_receivable_amount": 1.5537,
    "avatar": "https://i.pravatar.cc/150?img=7",
    "first_name": "Veronica ",
    "last_name": " Watts",
    "email": "veronicawatts@dancerity.com",
    "phone": "+1 (946) 447-3807",
    "mobile": "+1 (942) 559-3388",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b5225f99ea47a611b4db",
    "contact_name": "Eugenia",
    "company_name": "JUNIPOOR",
    "contact_type": "customer",
    "status": false,
    "payment_terms": 3,
    "payment_terms_label": "Ut mollit voluptate irure aliquip.",
    "currency_id": "61b8b522818899183ddfe4ef",
    "currency_code": "USD",
    "outstanding_receivable_amount": 9,
    "unused_credits_receivable_amount": 3.8336,
    "avatar": "https://i.pravatar.cc/150?img=5",
    "first_name": "Lott ",
    "last_name": " Roman",
    "email": "lottroman@junipoor.com",
    "phone": "+1 (981) 507-3136",
    "mobile": "+1 (876) 461-2605",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b522c55f4e6ddd544359",
    "contact_name": "Margie",
    "company_name": "IDETICA",
    "contact_type": "customer",
    "status": false,
    "payment_terms": 6,
    "payment_terms_label": "Elit Lorem in cillum dolor.",
    "currency_id": "61b8b52233d54fb86be3b547",
    "currency_code": "USD",
    "outstanding_receivable_amount": 2,
    "unused_credits_receivable_amount": 3.1263,
    "avatar": "https://i.pravatar.cc/150?img=10",
    "first_name": "Rojas ",
    "last_name": " Elliott",
    "email": "rojaselliott@idetica.com",
    "phone": "+1 (930) 429-2007",
    "mobile": "+1 (992) 583-2140",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b522badefd60127ac2af",
    "contact_name": "Liliana",
    "company_name": "AQUACINE",
    "contact_type": "customer",
    "status": true,
    "payment_terms": 5,
    "payment_terms_label": "Deserunt duis esse enim sunt mollit.",
    "currency_id": "61b8b52224b2560f06846f83",
    "currency_code": "USD",
    "outstanding_receivable_amount": 5,
    "unused_credits_receivable_amount": 8.5699,
    "avatar": "https://i.pravatar.cc/150?img=3",
    "first_name": "Rasmussen ",
    "last_name": " Boone",
    "email": "rasmussenboone@aquacine.com",
    "phone": "+1 (890) 578-2919",
    "mobile": "+1 (922) 500-3088",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b522c83d0dd285433e0a",
    "contact_name": "Sanchez",
    "company_name": "MICROLUXE",
    "contact_type": "customer",
    "status": false,
    "payment_terms": 7,
    "payment_terms_label": "Eiusmod eu velit consectetur dolor velit ex consequat irure qui ipsum id nulla ullamco officia.",
    "currency_id": "61b8b52273d6725bd39940e5",
    "currency_code": "USD",
    "outstanding_receivable_amount": 7,
    "unused_credits_receivable_amount": 4.6167,
    "avatar": "https://i.pravatar.cc/150?img=4",
    "first_name": "Kitty ",
    "last_name": " Rodgers",
    "email": "kittyrodgers@microluxe.com",
    "phone": "+1 (917) 535-2823",
    "mobile": "+1 (959) 598-2415",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  },
  {
    "contact_id": "61b8b522c87245e6241aacfa",
    "contact_name": "Angelita",
    "company_name": "SEALOUD",
    "contact_type": "customer",
    "status": false,
    "payment_terms": 10,
    "payment_terms_label": "Commodo quis enim minim proident ut laboris veniam eu proident in irure dolor exercitation consectetur.",
    "currency_id": "61b8b5223549a0f02aa8c268",
    "currency_code": "USD",
    "outstanding_receivable_amount": 2,
    "unused_credits_receivable_amount": 0.9503,
    "avatar": "https://i.pravatar.cc/150?img=8",
    "first_name": "Bolton ",
    "last_name": " Prince",
    "email": "boltonprince@sealoud.com",
    "phone": "+1 (953) 561-3184",
    "mobile": "+1 (983) 550-2367",
    "created_time": "<SyntaxError: missing ) after argument list>",
    "last_modified_time": "<SyntaxError: missing ) after argument list>"
  }
]
// [
//   '{{repeat(5, 20)}}',
//   {  
//       contact_id: '{{objectId()}}',
//     contact_name:'{{firstName()}}',
//     company_name: '{{company().toUpperCase()}}',
//     contact_type: "customer",
//     status: '{{bool()}}',
//     payment_terms: "15",
//     payment_terms_label: "Net 15",
//     currency_id: "460000000000097",
//     currency_code: "USD",
//     outstanding_receivable_amount: "250",
//     unused_credits_receivable_amount: "1369.66",
//     avatar:'http://placehold.it/32x32',
//     first_name:'{{firstName()}} ',
//     last_name:' {{surname()}}',
//     email: '{{email()}}',
//     phone:'+1 {{phone()}}',
//     mobile:'+1 {{phone()}}',
//     created_time:'{{date(new Date(2014, 0, 1), new Date(), YYYY-MM-ddThh:mm:ss Z)}}',
//     last_modified_time:'{{date(new Date(2014, 0, 1), new Date(), YYYY-MM-ddThh:mm:ss Z)}}'
  
//   }
// ]
export { ContactsData };
